[package]
versioned_files = [
    { path = "LosslessCutLauncher/LosslessCutLauncher.csproj", regex = '<AssemblyVersion>(?<version>\d+\.\d+\.\d+)</AssemblyVersion>' },
]
changelog = "CHANGELOG.md"
extra_changelog_sections = [
    { name = "Documentation", types = [
        "docs",
    ] },
    { name = "Notes", types = [
        "note",
    ] },
]
assets = "release-assets/*"

[changes]
ignore_conventional_commits = true

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "Command"
command = "git switch -c release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release $version\""

[[workflows.steps]]
type = "Command"
command = "git push --force --set-upstream origin release"

[[workflows.steps]]
type = "CreatePullRequest"
base = "main"

[workflows.steps.title]
template = "chore: prepare release $version"

[workflows.steps.body]
template = "Merging this PR publishes the release.\n\n$changelog"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[github]
owner = "hazre"
repo = "lossless-cut-launcher"

[release_notes]
change_templates = [
    "### $summary <!-- commit:$commit_hash -->\n\n$details",
    "* $summary <!-- commit:$commit_hash -->",
]
